lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 97200 # token TTL in seconds, defaults to 1 hour
    #    token_ttl: 120 # token TTL in seconds, defaults to 1 hour
    user_identity_field: phone  # key under which the user identity will be stored in the token payload
    clock_skew: 0

    # token encoding/decoding settings
    encoder:
        # token encoder/decoder service - default implementation based on the lcobucci/jwt library
        service: lexik_jwt_authentication.encoder.lcobucci

        # encryption algorithm used by the encoder service
        signature_algorithm: RS256

        # token extraction settings
    token_extractors:
        # look for a token as Authorization Header
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization

            # check token in a cookie
        cookie:
            enabled: true
            name: bearer



            # check token in query string parameter
        query_parameter:
            enabled: false
            name: bearer

            # check token in a cookie
        split_cookie:
            enabled: true
            cookies:
                - jwt_hp
                - jwt_s
    #    set_cookies:

    set_cookies:
        jwt_hp:
            lifetime: 97200
            #            lifetime: 120
            samesite: strict
            path: /
            domain: my-record.dev
            httpOnly: false
            split:
                - header
                - payload

        jwt_s:
            lifetime: 97200
            #            lifetime: 120
            samesite: strict
            path: /
            domain: my-record.dev
            httpOnly: true
            split:
                - signature
        bearer:
            domain: my-record.dev